/**
 * Mock data phản ánh schema GatewayRouteEntity + RBAC.
 * Permission = resource + action (không có role). Role gán qua auth role_permissions.
 */

export const MOCK_PERMISSIONS = [
  { id: 1, resource: 'products', action: 'READ',   code: 'products:READ' },
  { id: 2, resource: 'products', action: 'CREATE', code: 'products:CREATE' },
  { id: 3, resource: 'orders',   action: 'READ',   code: 'orders:READ' },
  { id: 4, resource: 'users',    action: 'READ',   code: 'users:READ' },
  { id: 5, resource: 'orders',   action: 'CREATE', code: 'orders:CREATE' },
  { id: 6, resource: 'profile',  action: 'READ',   code: 'profile:READ' },
  { id: 7, resource: 'profile',  action: 'UPDATE', code: 'profile:UPDATE' },
]

export const MOCK_ROUTES = [
  {
    id: 'auth-login',
    uri: 'http://localhost:8081',
    predicates: '[{"name":"Path","args":{"pattern":"/api/auth/login"}},{"name":"Method","args":{"methods":"POST"}}]',
    filters: '[{"name":"Retry","args":{"retries":"3","statuses":"SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT"}},{"name":"CircuitBreaker","args":{"name":"fastOpenCB","fallbackUri":"forward:/fallback/auth"}}]',
    routeOrder: 1,
    enabled: true,
    permissionIds: [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'auth-register',
    uri: 'http://localhost:8081',
    predicates: '[{"name":"Path","args":{"pattern":"/api/auth/register"}},{"name":"Method","args":{"methods":"POST"}}]',
    filters: '[{"name":"CircuitBreaker","args":{"name":"fastOpenCB","fallbackUri":"forward:/fallback/auth"}}]',
    routeOrder: 2,
    enabled: true,
    permissionIds: [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'auth-refresh',
    uri: 'http://localhost:8081',
    predicates: '[{"name":"Path","args":{"pattern":"/api/auth/refresh"}},{"name":"Method","args":{"methods":"POST"}}]',
    filters: '[{"name":"CircuitBreaker","args":{"name":"fastOpenCB","fallbackUri":"forward:/fallback/auth"}}]',
    routeOrder: 3,
    enabled: true,
    permissionIds: [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'auth-logout',
    uri: 'http://localhost:8081',
    predicates: '[{"name":"Path","args":{"pattern":"/api/auth/logout"}},{"name":"Method","args":{"methods":"POST"}}]',
    filters: '[{"name":"CircuitBreaker","args":{"name":"fastOpenCB","fallbackUri":"forward:/fallback/auth"}}]',
    routeOrder: 4,
    enabled: true,
    permissionIds: [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'auth-validate',
    uri: 'http://localhost:8081',
    predicates: '[{"name":"Path","args":{"pattern":"/api/auth/validate"}},{"name":"Method","args":{"methods":"GET"}}]',
    filters: '[{"name":"Retry","args":{"retries":"3"}},{"name":"CircuitBreaker","args":{"name":"fastOpenCB","fallbackUri":"forward:/fallback/auth"}}]',
    routeOrder: 6,
    enabled: true,
    permissionIds: [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'resource-service',
    uri: 'http://localhost:8082',
    predicates: '[{"name":"Path","args":{"pattern":"/api/resources/**"}}]',
    filters: '[{"name":"Retry","args":{"retries":"3","statuses":"SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT"}},{"name":"CircuitBreaker","args":{"name":"slowOpenCB","fallbackUri":"forward:/fallback/resource"}}]',
    routeOrder: 10,
    enabled: true,
    permissionIds: [1, 3, 5, 6, 7],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'oauth2-authorization',
    uri: 'http://localhost:8081',
    predicates: '[{"name":"Path","args":{"pattern":"/oauth2/**"}}]',
    filters: '[{"name":"CircuitBreaker","args":{"name":"fastOpenCB","fallbackUri":"forward:/fallback/auth"}}]',
    routeOrder: 8,
    enabled: false,
    permissionIds: [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]
