events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Tự động chuyển hướng HTTP sang HTTPS
    server {
        listen 80;
        server_name localhost; # Thay bằng domain của bạn
        return 301 https://$host$request_uri;
    }

    # Cấu hình HTTPS Proxy
    server {
        listen 443 ssl;
        server_name localhost; # Thay bằng domain của bạn

        # Đường dẫn tới file .crt và .key đã mount vào container
        ssl_certificate     /etc/nginx/certs/auth-service.crt;
        ssl_certificate_key /etc/nginx/certs/auth-service.key;

        # Cấu hình bảo mật SSL cơ bản
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            # Tên service và cổng nội bộ khai báo trong docker-compose.yml
            proxy_pass http://rbac-auth:8081; 
            
            # Chuyển tiếp các header cần thiết
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
